name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install tkinter
      run: sudo apt-get install python3-tk
      
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install transformers PyPDF2 llama-toolchain
            

    - name: App.py
      working-directory: App
      run: python main.py





